### ISSUE TITLE
SQUID3 stating .xml file does not have any masses?

### ISSUE THREAD

**Issue by nmseymour** [CIRDLES/Squid#578] opened 2021-02-02 18:17 UTC
Hi all,

I am new to SHRIMP-RG and SQUID, so please bear with me. I am trying to process a recent U-Pb run. I have two .xml files - one for the concentration standard MAD-559, which I created a new concentration standard file for, and one for all the measurements. I have 10 peaks - standard 9 plus Au. When I move from the data to the task file, SQUID3 informs me that my files do not have any masses - specifically "The data file has 0 masses, this task requires 10". I have not modified the .xml file at all, and as far as I can see it does indeed have masses, so I do not know where to go from here. I am attaching the .xml files for reference.
[Archive.zip](https://github.com/CIRDLES/Squid/files/5913471/Archive.zip)

Thanks!

**Comment by NicoleRayner** [comment] 2021-02-02 18:25
Hi there!  Thanks for posting.  I think these are our first xml files off the SHRIMP RG so will be a valuable tool for us. I'm going to poke around and see what happens for me.

**Comment by NicoleRayner** [comment] 2021-02-02 19:11
OK - so if I only process your .xml that contains the data from your **unknowns + Temora only** it works fine.  And if I try and open the CRM file only, it works fine. The problem seems to be the combination of the two.  Notably, the can't do the Data Audit with the combined file, though I can for the individual files, so the problem is even before the "Task" part of squid3, it is in the reading of the combined file.  When I try and load the "joined" xml (instead of selecting the 2 individual ones" I get the following error message:
![image](https://user-images.githubusercontent.com/40035242/106649453-9ae61300-655f-11eb-8ff7-76d55cd52a54.png)
And here is the "joined" xml here in case this helps @bowring with a bit of troubleshooting.
[Alan Chapman_AC_20112411.46-JOIN-Alan Chapman_AC_20112415.00.zip](https://github.com/CIRDLES/Squid/files/5913873/Alan.Chapman_AC_20112411.46-JOIN-Alan.Chapman_AC_20112415.00.zip)

**Comment by bowring** [comment] 2021-02-02 20:20
I have found the issue with not being able to correctly open the two files together as a merge operation, but when I then do as @NicoleRayner says and open the merged file, all is well.  I examined the attached file and found that it has been truncated.  I am attaching the correct file for comparison, which does open
[Alan Chapman_AC_20112411.46-JOIN-Alan Chapman_AC_20112415.00-verified.xml.zip](https://github.com/CIRDLES/Squid/files/5914229/Alan.Chapman_AC_20112411.46-JOIN-Alan.Chapman_AC_20112415.00-verified.xml.zip)
.  The next version v1.7.2 will have the merge problem fixed.

**Comment by NicoleRayner** [comment] 2021-02-02 20:42
Thanks Jim.  I repeated the same steps as before and reloaded the joined file and it worked for me this time too.  Not sure how that got truncated.   Anyway good to know problem solved.

**Closed** 2021-02-02 21:20 UTC
Labels: bug

**Comment by bowring** [comment] 2021-02-02 21:41
@nmseymour - version v1.7.2 has your fix - use "Project / New Squid3 GEOCHRON Project / By Joining two Prawn XML files" !

**Comment by nmseymour** [comment] 2021-02-02 22:48
Excellent, thank you!
