### ISSUE TITLE
Uncorrected 208Pb232Th is really 204corrected?!

### ISSUE THREAD

**Issue by auscopegeochemistry** [CIRDLES/Squid#585] opened 2021-02-16 06:15 UTC
When creating a custom rapport I'd like to export the Total_208Pb232Th ratio. Looking at the expression used to calculate the ratio the resultant is a 204corrected ratio, is there an uncorrected ratio available?

Cheers,
Alexander Prent
![image](https://user-images.githubusercontent.com/56670011/108025395-5ed3a780-7061-11eb-840a-ef657e7001a5.png)

**Comment by cwmagee** [comment] 2021-02-16 06:55
There is a 208/248 column over on the left, but that is not calibrated in any way.

**Comment by sbodorkos** [comment] 2021-02-16 14:42
Hi Alex @auscopegeochemistry , the problem here is that any representation of a 'true' daughter/parent ratio (i.e. 206/238 or 208/232) relies on a calibration relationship, and when you reduce the data for your reference material, you're obliged to select an 'index isotope' with which to perform the common Pb correction. It's a necessary step firstly because you need your RM-based calibration to be as accurate as possible, and secondly because the 'true' daughter/parent ratio measured in the reference material (usually via IDTIMS) is *always* itself corrected for common Pb.

Calibration constants are utilised by assuming that the relationship between the true and measured ratios for any given unknown spot is identical to the relationship between the true and measured ratios on the reference material. With respect to *spot-specific* "Total 206Pb/238U" in the unknowns, the relationship looks like:

`[SpotUnkTotal206/238] / [SpotUnk206/238CalibConst] = [RefRM206*/238] / [MeanRM206*/238CalibConst]`

where

- `[SpotUnkTotal206/238]` is the 'true' (and *not* corrected for common Pb) value of 206/238 for the unknown spot.
- `[SpotUnk206/238CalibConst]` is the measured 206/238 calibration constant (also *not* corrected for common Pb) for the unknown spot.
- `[RefRM206*/238]` is the 'true' value of 206/238 for the reference material (determined by IDTIMS, and it *is* corrected for common Pb).
- `[MeanRM206*/238CalibConst]` is the mean 206/238 calibration constant for the population of reference material analyses, and it *is* corrected for common Pb, because `[RefRM206*/238]` is.

Essentially, the problem is that `[MeanRM206*/238CalibConst]` can have very slightly different values depending on which 'index isotope' you choose in order to reduce your reference material analyses. And as you can see from the above equation, those small differences will propagate to `[SpotUnkTotal206/238]`.

Fortunately, once you do settle on your 'index isotope' for your reference material (and you need to make this decision before you consider data from your unknowns in any case), you also lock down your `[SpotUnkTotal206/238]` value. The relationship is always one-to-one; there is never more than one `[Total_206Pb238U]` value in existence at any one time, it's just that its exact value is dictated by your 'index isotope' choice on the reference material.

Squid3 handles this for you: try changing the index isotope from 204Pb to 207Pb (e.g. using the radio buttons in the Reference Material Weighted Average window), and then revisit the Expression Manager: you should see that `[Total_206Pb238U]` has changed to = `[7cor_Total_206Pb238U]`.

Finally, if you're wondering why this post is all about 206/238 when you asked about 208/232, it's because the index isotope dependency emerges during the primary calibration (which is usually 206/238) and then contaminates all downstream calculations. The calculation you are looking at is:

`[SpotUnkTotal208/232] = [SpotUnkTotal206/238] * [SpotUnkTotal208/206] / [SpotUnk232/238]`

On the right-hand side, the second term is truly uncorrected for common Pb, and the third term contains no Pb at all. But unfortunately the first term has a a minor dependency on the index isotope of the reference material as outlined above, which means that the term on the left-hand side inherits that dependency.

**Comment by NicoleRayner** [comment] 2021-02-17 13:45
I just want to add that a great way to understand these expressions is to use the "show expression details" button in the upper right of the Expression Manager. 
![image](https://user-images.githubusercontent.com/40035242/108212856-61cfa600-70fc-11eb-9d76-fab4336f13fe.png)

From there you can follow the breadcrumbs that the 4cor refers to the index isotope selected for the RM calibration, not a correction on the unknown.  That nomenclature got me at the start too....

**Comment by auscopegeochemistry** [comment] 2021-02-18 03:57
Hi Simon @sbodorkos and Nicole @NicoleRayner, thank you for that thorough explanation! 

It's complex but at the same time straightforward. 

Thanks again!

**Comment by bowring** [comment] 2021-03-02 17:24
@auscopegeochemistry - should we close this issue?

**Closed** 2021-03-18 21:15 UTC
Labels: discussion, question
