### ISSUE TITLE
Possible bug Common Pb for unknowns

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#400] opened 2020-01-20 01:30 UTC
I noticed that the concordia diagram for the unknowns does not change when I change the assign common Pb ratios for the unknowns. When I returned to the assign common Pb window the selected common Pb had reverted back to the original setting. As a test, I put in a Crazy Common Pb Model (6-4 200, 7-4 100, 8-6 40) and again there was no change to the concordia diagram for the unknowns. When I chose the Crazy Common Pb model for the standard the concordia for the standard changed.

**Comment by bowring** [comment] 2020-01-20 01:51
Can you send some example files thanks

**Comment by NicoleRayner** [comment] 2020-01-20 18:30
I'm not sure if this is related, but when I select a new common Pb model for the Unknowns as a whole, it does not change the selection for the individual samples,  I have to change each one manually, but when I do it does take it and change the concordia diagram appropriately.

Interestingly if I change the RM common Pb to the "Crazy common Pb model", and then I try and plot the concordia diagram for the RM, I get the blue intro screen as described in issue #393

**Comment by bowring** [comment] 2020-01-22 20:37
This issue is fixed in release v1.4.4;  The cause of the blue screen was related to an unanticipated bug in the expression parsing and evaluation algorithms arising when certain expressions appeared well-formed, but actually caused failure.  @NicoleRayner please note that the following expression in your example project: "1242 WtdAv 7/6 ratio" is not specified as a summary expression, which it is.

**Closed by bowring** 2020-01-22 20:37 UTC
