### ISSUE TITLE
Aliased Expressions not implemented properly

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#664] opened 2021-11-14 13:23 UTC
@bowring Long ago, when unravelling the detail of Expression dependencies, we found that columns such as "Total 206Pb/238U" for unknowns actually have a subtle dependency on the index isotope used for the common Pb correction. So for a Perm1 Task (U-Pb geochronology, with no independent Th-Pb calibration), there are three candidate values for "Total 206Pb/238U" for unknowns: 4cor_Total_206Pb_238U, 7cor_Total_206Pb_238U, and 8cor_Total_206Pb_238U.

Depending on the index isotope chosen by the user, exactly one of these values is selected to use the alias "Total_206Pb_238U". The problem, as portrayed by the Expression Manager at present, is that the relevant expression is defined simply as:

`4cor_Total_206Pb_238U`

when it should really be something like:

`ValueModel ( ["4cor_Total_206Pb_238U"], [%"4cor_Total_206Pb_238U"], false )`

in order to portray not just the aliased value but also the aliased uncertainty, as it should. The same problem affects Total_208Pb_232Th and Total_207Pb_206Pb, for both Reference Materials and Unknowns. 

Note that it does **not** affect Total_238U_206Pb: seemingly, the need to invert the Value of Total_206Pb_238U resulted in the entire expression being formulated correctly.

My Project file (as an example of the issue) is here: **[170111_GA6357_Sq3-190.zip](https://github.com/CIRDLES/Squid/files/7533791/170111_GA6357_Sq3-190.zip)**

I noticed the issue when viewing the CSV output of my Unknowns report, created using the "BuiltIn_revSQ2.50_SampleData" template.

**Comment by bowring** [comment] 2021-11-14 16:44
It seems the issue is merely that the peek window in expressions and the report manager don't report the uncertainty values of the underlying expression.  In expression manager if you use "T" and hover over "4cor_Total_206Pb_238U". you will see the full expression and values as if you examined the expression 4cor_Total_206Pb_238U itself.  Good catch.

**Comment by bowring** [comment] 2021-11-15 10:42
Fixed in v1.9.1

**Closed by bowring** 2021-11-15 10:42 UTC
