### ISSUE TITLE
CUSTOM EXPRESSION MISSING IN CUSTOM REPORT 

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#543] opened 2020-12-19 06:35 UTC
I must be missing where to find the TotREEcpsRM and TotREEcpsunk in the Custom Report Builder. They are in the Custom Expressions. I will forward two screen shots to Nicole showing this. 
PS how do I attach screen shots here?

**Comment by sbodorkos** [comment] 2020-12-19 10:31
Hi @AllenKennedy are your 'TotREE... ' expressions healthy, or are they hiding in the Unhealthy Expressions section on the left?

With respect to screenshots, if you're in Windows, you should be able to use the Snipping Tool, then select Edit... from its Copy menu (or just Ctrl-C), then come into one of these thread-reply windows, position the cursor in here, and then press Ctrl-V. You'll see a brief message saying 'Uploading user png' or similar, which then changes to a string that will look like this:

![image](https://user-images.githubusercontent.com/17473203/102687190-7cdb8200-4241-11eb-86f1-4c0336b0a1f3.png)

But when you press Comment, the post will appear with your actual screenshot instead:

![image](https://user-images.githubusercontent.com/17473203/102687154-3554f600-4241-11eb-82c1-f7c8768a646f.png)

**Comment by bowring** [comment] 2020-12-19 13:03
Here again, having actual files will make it easier to understand what you are experiencing.  @AllenKennedy - Thanks for all your stress testing!!

**Comment by NicoleRayner** [comment] 2020-12-22 16:37
@AllenKennedy sent me the .squid file via email (I attach it here as a .zip) and I cannot reproduce his problem (I can see all custom expressions in the report builder).  As you can see in the screenshot he sent me, he doesn't seem to have a scroll bar beside the custom expressions indicating that there are more of them.  <img width="1251" alt="CUSTOM REPORT Screen " src="https://user-images.githubusercontent.com/40035242/102911206-b7177000-4449-11eb-9744-3d65bea8b930.png">

I do have such a scroll bar but it is ever so slightly truncated along the long edge.

I am wondering if he has a display resolution problem that is making his scroll bar disappear so suggest he tries selecting a custom expression in report builder and using up/down arrows to cycle through.  I tried mucking around with my screen resolution to see if I could confirm that as a problem, but could not.  

[3.3 27peak xeno.squid.zip](https://github.com/CIRDLES/Squid/files/5730981/3.3.27peak.xeno.squid.zip)

**Comment by bowring** [comment] 2020-12-22 17:09
It is possible to move the horizontal and vertical dividers with the mouse and cause the lists to repaint which might solve the problem.  @AllenKennedy - it would help to know operating system and Java version in case this is a quirky bug.

**Comment by NicoleRayner** [comment] 2020-12-22 17:18
FWIW, I cannot move the vertical divider in the Report Builder, I can move the horizontal ones.  In the Expression Manager I can move all.  Windows 10, Java 1.8.

**Comment by AllenKennedy** [comment] 2020-12-24 00:20
When I expanded my window to the max size the slide bar appeared. I am using a MacBook Pro with OS X Yosemite 10.10.5 Java 1.8

**Comment by AllenKennedy** [comment] 2020-12-24 00:23
Expressions manager worker perfectly, even when Custom Reports doesn't

**Comment by bowring** [comment] 2020-12-25 16:04
FYI, you should be able to use your scroll wheel in the pane of custom expressions to move up and down even if you don't see the scroll bar.  Fix is in the works.

**Closed** 2020-12-28 13:38 UTC
Labels: bug
